name: Release code

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: docker
    services:
      dind:
        image: docker:dind
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code using Git
        uses: actions/checkout@main

      - name: Install Docker
        run: |
          apt update
          apt-get install -y docker.io
          docker context create forgejo --docker host=tcp://dind:2375
          docker context use forgejo

      - name: Log in to our container registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.terah.dev
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker images
        run: |
          docker build ./backend --tag git.terah.dev/imterah/hermes:$GITHUB_REF_NAME
          docker build ./sshfrontend --tag git.terah.dev/imterah/hermes-lom:$GITHUB_REF_NAME

      - name: Upload all Docker images
        run: |
          docker tag git.terah.dev/imterah/hermes:$GITHUB_REF_NAME git.terah.dev/imterah/hermes:latest
          docker push git.terah.dev/imterah/hermes:$GITHUB_REF_NAME
          docker push git.terah.dev/imterah/hermes:latest

          docker tag git.terah.dev/imterah/hermes-lom:$GITHUB_REF_NAME git.terah.dev/imterah/hermes-lom:latest
          docker push git.terah.dev/imterah/hermes-lom:$GITHUB_REF_NAME
          docker push git.terah.dev/imterah/hermes-lom:latest
