name: Release code

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: docker
    services:
      dind:
        image: docker:dind
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code using Git
        uses: actions/checkout@main

      - name: Install Docker
        run: |
          apt update
          apt-get install -y docker.io
          docker context create forgejo --docker host=tcp://dind:2375
          docker context use forgejo

      - name: Log in to our container registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: ghcr.io
          username: imterah
          password: ${{secrets.ACTIONS_PACKAGES_DEPL_KEY}}

      - name: Build Docker images
        run: |
          docker build ./backend --tag ghcr.io/imterah/hermes:$GITHUB_REF_NAME
          docker build -t ghcr.io/imterah/hermes-backend-migration:$GITHUB_REF_NAME -f MigrationDockerfile .

          docker build ./sshfrontend --tag ghcr.io/imterah/hermes-lom:$GITHUB_REF_NAME

      - name: Upload all Docker images
        run: |
          docker tag ghcr.io/imterah/hermes:$GITHUB_REF_NAME ghcr.io/imterah/hermes:latest
          docker push ghcr.io/imterah/hermes:$GITHUB_REF_NAME
          docker push ghcr.io/imterah/hermes:latest

          docker tag ghcr.io/imterah/hermes-backend-migration:$GITHUB_REF_NAME ghcr.io/imterah/hermes-backend-migration:latest
          docker push ghcr.io/imterah/hermes-backend-migration:$GITHUB_REF_NAME
          docker push ghcr.io/imterah/hermes-backend-migration:latest

          docker tag ghcr.io/imterah/hermes-lom:$GITHUB_REF_NAME ghcr.io/imterah/hermes-lom:latest
          docker push ghcr.io/imterah/hermes-lom:$GITHUB_REF_NAME
          docker push ghcr.io/imterah/hermes-lom:latest
